### ISSUE TITLE
BUG - Error al ejecutar Test de Persistencia 

### ISSUE THREAD

**Issue by nadiagutierrez89** [nadiagutierrez89/TP.DDS.2017.Grupo7#11]
AL ejecutar los Test de Persistencia por segunda vez (es decir cuando ya hay datos en la base), arroja error con el siguiente trace:

java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : ar.edu.utn.frba.dds.tp.dominio.Cuenta.empresa -> ar.edu.utn.frba.dds.tp.dominio.Empresa
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1760)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:458)
	at ar.edu.utn.frba.dds.tp.dominio.Repositorio.buscarUserPorId(Repositorio.java:414)
	at ar.edu.utn.frba.dds.tp.dominio.Aplicacion.guardarUnIndicador(Aplicacion.java:92)
	at ar.edu.utn.frba.dds.tp.test.TestPersistencia.testGuardarIndicador(TestPersistencia.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : ar.edu.utn.frba.dds.tp.dominio.Cuenta.empresa -> ar.edu.utn.frba.dds.tp.dominio.Empresa
	at org.hibernate.engine.spi.CascadingActions$8.noCascade(CascadingActions.java:398)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:129)
	at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:432)
	at org.hibernate.event.internal.DefaultPersistEventListener.justCascade(DefaultPersistEventListener.java:188)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsPersistent(DefaultPersistEventListener.java:181)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:145)
	at org.hibernate.internal.SessionImpl.firePersistOnFlush(SessionImpl.java:838)
	at org.hibernate.internal.SessionImpl.persistOnFlush(SessionImpl.java:831)
	at org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:357)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:350)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:293)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:379)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:319)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:296)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:118)
	at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:167)
	at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:158)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:91)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:61)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1191)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1257)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:449)
	... 28 more

**Comment by bstolarz** [comment]
Cuando corro especificamente el test TestPersistencia.cargarActualizarJSONEmpresasYCuentasABaseDeDatos,
a veces me tira el error de IllegalState: object references an unsaved transient instance - save the transient instance before flushing 
y otras veces me tira el error  java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)

**Comment by bstolarz** [comment]
Entiendo que cuando cargamos el JSON al repositorio en memoria, deberiamos linkearlo con Hibernate, para que al persistir, Hibernate reconozca que existen como objetos, y que ejecuten un UPDATE. Ahora pareciera que no existen en memoria y Hibernate no sabe qué hacer con ellos.

**Comment by bstolarz** [comment]
Issue fixed!
estabamos creando nuevos objetos distintos a los que tenia Hibernate, entonces al duplicarse, habian objetos que quedaban desreferenciados.

**Comment by martinaguero** [comment]
👍!!
